# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20160907_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '新闻文章', 'verbose_name_plural': '新闻文章'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['name'], 'verbose_name': '新闻分组', 'verbose_name_plural': '新闻分组'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FilePathField(default='', verbose_name='图片路径'),
        ),
    ]
