# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20160908_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to=None, verbose_name='图片路径'),
        ),
    ]
