# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20160908_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.CharField(default='', max_length=256, verbose_name='关键字'),
        ),
    ]
