# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='Images', verbose_name='图片路径'),
        ),
    ]
