# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20160910_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='333', max_length=256, verbose_name='图片名称'),
            preserve_default=False,
        ),
    ]
